### ISSUE TITLE
Why remove Mac OSX support?

### ISSUE THREAD

**Issue by ksylvan** [dhoer/chef-appium#2]
I noticed in the commit log, this commit https://github.com/dhoer/chef-appium/commit/b5fb5f69898e958f6d49085f20377e6522af42b2

Why remove Mac OSX support? What was the problem?

**Comment by dhoer** [comment]
I have no idea why I did that.  Not a good commit message. There might have been issues with nodejs?  If you would like to submit a PR with it back in, I would accept it.

**Comment by ksylvan** [comment]
This repo is inactive and I'm closing old issues I submitted way back.
